### ISSUE TITLE
visibility: hidden & display: none 的区别:

### ISSUE THREAD

**Issue by super-fool** [super-fool/blog#14]
visibility: hidden 只是隐藏了元素,但会保留其位置,不会去改变布局.
display: none 会隐藏元素, 不会保留位置, 其余元素会填补位置.

当然,这只是大家都知道的区别, OK, 那么我们看看我们不知道的区别:
---
### 子元素会不会隐藏呢?
```css
/* inner 是 outer 的子元素 */
.outer {
  visibility: hidden;
  display: none;
}
.outer .inner {
  visibility: visible;
}
```
我们将outer的两个属性来回切换看看, 是不是发现了?
如果父元素是`hidden`, 子元素是`visible`. 还是会显示子元素的.
但是父元素是`none`, 子元素就算是`visible`也是会被隐藏! 验证了古代的一句话: 皮之不存,毛将焉附?

### 绑定的事件会不会触发呢?

答: 使用`display | visibility`都不会触发绑定的事件, 但是, 如果像父元素是隐藏(`visibility: hidden`), 但是子元素是显示的(`visibility: visible`). 那么子元素是可以触发事件的!
还有一个属性`opacity: 0`. 这个伪隐藏是可以触发事件的!

---
