### ISSUE TITLE
css经验总结

### ISSUE THREAD

**Issue by super-fool** [super-fool/blog#16]
### 实现图片占满屏幕宽度.
```css
.img {
  max-width: 100%;
  margin: 0 auto;
  diaplay: block;
}
```
我一开始直接用`width:100%`, 但是我发现如果在可伸缩的情况下, 宽度便定了型. 所以最好使用`max-width: 100%`. 当屏宽大于了图片宽, 图片便会**默认的居左显示**, 所以我们还得需要`margin: 0 auto;`.

`display: block;`如果我们使用`ul`中的`li`来包裹着每一个`img`. 那么我们会发现,每一个图片之间都是**留有空白**, 就是因为img是一个行内元素. 所以我们需要使用`block`来解决空白的问题.
