### ISSUE TITLE
CSS 样式总结

### ISSUE THREAD

**Issue by super-fool** [super-fool/blog#55]
禁止用户选中文字:
```css
.non-select {
  -webkit-user-select: none;
}
```
1. none: 禁止选中
2. all: 整个标签内容选中
3. text: 默认,指定选中
