### ISSUE TITLE
CSS- 弹出框居中

### ISSUE THREAD

**Issue by super-fool** [super-fool/blog#6]
<h1 align='center'>弹出框居中方案</h1>

```css
/* <!-- 通用遮罩层 --> */
.mask {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  top: 0;
  background-color: rgba(0, 0, 0, 0.6);
}
```

### 方案 1:

```css
.popup-container {
  position: absolute;
  top: 50%;
  transform: translateY(-50%); // 随弹出框内容垂直居中

  left: 0;
  right: 0;
  width: 70%;
  margin: 0 auto; // 水平居中

  background-color: #e6ef99;
  border-radius: 20px;
}
```

###  🌰:

<img src="https://github.com/super-fool/blog/blob/master/css-1.png?raw=true" width=256 height=456 />

1. 首先要清楚这个弹出框的内容有哪些, 这个 🌰 中其实就只有一个弹出框, 里面分为展示内容区和下载的按钮区.

```css
//  整个弹出框
.popup-container {
  position: absolute;
  top: 50%;
  transform: translateY(-50%); // 随弹出框内容垂直居中
  left: 0;
  right: 0;
}
//  弹出框的内容区
.popup-container .popup-content {
  position: relative;
  width: 70%:
  margin: 0 auto 20px; 离下载按钮区有20px间距.  
}
//  下载按钮区
.popup-container .popup-download {
  display: block;
  width: 50%;
  margin: 0 auto;
}
```
